name: App

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    paths:
      - '**.md'
      - 'infra/**'
      - '.terraform-version'
      - '.github/workflows/infra.yml'

permissions: read-all

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
